---
name: Release Charts
'on':
  push:
    branches:
      - release
jobs:
  release:
    permissions:
      contents: write
      packages: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Add repositories
        run: |
          helm dependency list --max-col-width 10000 "./charts/nifi" | awk 'NR>1 {print $1,$3}' | while read -r name url; do
            if [[ -n "$name" && -n "$url" && "$url" != file* ]]; then
              helm repo add "$name" "$url"
            fi
          done
          helm dependency update "./charts/nifi"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          charts_dir: "charts"
